trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - mkdocs.yml
    - docs/*

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: Bash@3
    displayName: 'Build Script'
    inputs:
      filePath: './build.sh'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: './nupkg'
      ArtifactName: 'PackageDrop'
      publishLocation: 'Container'