trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - mkdocs.yml
    - docs/*

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: Bash@3
    displayName: 'Build Script'
    inputs:
      filePath: './build.sh'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: './nupkg'
      ArtifactName: 'PackageDrop'
      publishLocation: 'Container'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: './nupkg/*.nupkg;!./nupkg/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '09327a35-bd7e-4966-b5f1-e3fdd2b698c0/093a11ec-a3fd-4f31-9750-172459338097'