site_name: Blobfish1
site_url: https://github.com/theigner/Blobfish
site_description: Welcome to Blobfish
site_author: Thomas Eigner

repo_url: https://github.com/theigner/Blobfish
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - The AnIML format:
        - Top level collections: animl/toplevelcollections.md
    - Blobfish Quickstart:
        - Read an AnIML document: quickstart/readanimldoc.md
        - Create your first AnIML document: quickstart/createfirstanimldoc.md
        - Read an AnIML document: quickstart/validateanimldoc.md

plugins:
    - search